Small & Prechecked checkboxes
freeman14/dd-ui pull request #35
Opened 2016-12-29 17:27 UTC by okolomiets

![](https://i.gyazo.com/b59deb2c9c749aebd6e4e2681fbf68ec.png)

2016-12-30 08:19 UTC, freeman14 requested changes

2016-12-30 08:19 UTC, freeman14 commented on src/directives/checkbox/checkbox.partial.html
> +	<div class="dd__checkbox{{isSmall ? '--small': ''}}" ng-class="{'checked': isChecked}" ng-click="toggle()">
use additional class for modificator dd__checkbox--small

2016-12-30 08:19 UTC, freeman14 commented on src/styles/blocks/input.less
> -        max-width: calc(~"100% - "@labelMargin);
Why you remove this?

2016-12-30 08:19 UTC, freeman14 commented on src/styles/blocks/input.less
> -        max-width: calc(~"100% - "@labelMargin);
This using for calculate checkbox with with label and use `text-overflow: elipsis` for label

2016-12-30 08:19 UTC, freeman14 commented on stories/styleGuide/atoms/inputs.html
> +        <checkbox ng-model="model1">
don't use variables like `model1` and `myVar1`

2016-12-30 09:11 UTC, okolomiets commented on src/directives/checkbox/checkbox.partial.html
> +	<div class="dd__checkbox{{isSmall ? '--small': ''}}" ng-class="{'checked': isChecked}" ng-click="toggle()">
Fixed.

2016-12-30 09:12 UTC, okolomiets commented on src/styles/blocks/input.less
> -        max-width: calc(~"100% - "@labelMargin);
Reverted.

2017-01-04 14:25 UTC, freeman14 approved these changes

2017-01-07 14:45 UTC, merged