Error pages
freeman14/dd-ui pull request #47
Opened 2017-01-20 12:40 UTC by okolomiets

2017-01-20 15:32 UTC, freeman14 requested changes

2017-01-20 15:32 UTC, freeman14 commented on src/errorPage/notFound.component.ts
> +        this.templateUrl = './errorPage/notFound.partial.html';
Use template instead and require method to import template

2017-01-20 15:35 UTC, freeman14 requested changes

2017-01-20 15:35 UTC, freeman14 commented on sb/.webpack/webpack.dev.js
> +          'source' : path.resolve(__dirname, '..', '..', 'src/assets/images/'),
use `path.resolve(__dirname, '../../src/assets/images/')` instead

2017-01-20 15:35 UTC, freeman14 commented on src/errorPage/error.component.ts
> +        this.templateUrl = './errorPage/error.partial.html';
Same with `require`

2017-01-20 15:35 UTC, freeman14 commented on src/errorPage/maintenance.component.ts
> +        this.templateUrl = './errorPage/maintenance.partial.html';
Same with `require `

2017-01-23 08:09 UTC, okolomiets commented
Fixed

2017-01-23 12:47 UTC, freeman14 requested changes

2017-01-23 12:47 UTC, freeman14 commented on src/styles/components/error.less
> +    padding-left: 20px;
padding: 0 20px

2017-01-23 12:47 UTC, freeman14 commented on src/styles/components/error.less
> +    -webkit-box-shadow: none;
https://css-tricks.com/do-we-need-box-shadow-prefixes/

2017-01-23 12:47 UTC, freeman14 commented on src/styles/components/error.less
> +    margin-bottom: 40px;
margin: 10px 0 40px;

2017-01-23 12:47 UTC, freeman14 commented on src/styles/components/error.less
> +      margin-right: 10px;
margin: 0 10px;

2017-01-23 12:54 UTC, okolomiets commented
Fixed.

2017-01-23 12:55 UTC, merged