Basic dropdown
freeman14/dd-ui pull request #49
Opened 2017-01-20 16:29 UTC by freeman14

2017-01-20 16:34 UTC, kurpav requested changes

2017-01-20 16:34 UTC, pkurochka commented on src/directives/dropdown/dropdown.directive.ts
> +          angular.element(document.body).bind('click', (event) => {
add `scope.$on('$destroy')` and release all resources

2017-01-20 16:34 UTC, pkurochka commented on src/styles/blocks/dropdown.less
> +	box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.2);
As far as I remember there is no autoprefixer here, so please use mixins

2017-01-23 08:01 UTC, freeman14 commented on src/styles/blocks/dropdown.less
> +	box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.2);
https://css-tricks.com/do-we-need-box-shadow-prefixes/

2017-01-23 09:47 UTC, pkurochka commented on src/directives/dropdown/dropdown.directive.ts
> +          element.bind('click', (event) => {
I guess we should remove this listener as well.

2017-01-23 09:48 UTC, freeman14 commented on src/directives/dropdown/dropdown.directive.ts
> +          element.bind('click', (event) => {
?

2017-01-23 09:50 UTC, kurpav approved these changes

2017-01-23 09:50 UTC, freeman14 commented on src/directives/dropdown/dropdown.directive.ts
> +          element.bind('click', (event) => {
fixed

2017-01-23 09:52 UTC, merged